# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f75e8f35b0ed63b5265e18b963aef48348e0727b208236f881071f105dfcfc56c7dfa963a47aa337a9b5335e36ce88301ad75139e91c468cff5607987e1bef

test:
  secret_key_base: ab3cb543b358ac68e7712ff57af396cfef7129af9e06270a25cb7b5f879d79d67e7d4ea5418113cd70d25878f79e777af47d0a2147ad7d8947f9534ab6383394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
